<?
// $Id$
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file
 * Control a OpenX server from distance.
 */

/**
 * Implementation of hook_exit().
 */
function openx_manager_exit() {
  // Close the connextion with OpenX server, if opened.
  if (_openx_manager_session(TRUE)) {
    xmlrpc(
      'http://'. variable_get('openx_manager_server', '') .'/www/api/v1/xmlrpc/LogonXmlRpcService.php',
      'logoff',
      _openx_manager_session()
    );
  }
}

/**
 * Implementation of hook_menu().
 */
function openx_manager_menu() {
  $items['admin/settings/openx-manager'] = array(
    'access arguments'  => array('administer a OpenX server'),
    'description'       => 'Control a OpenX server from here',
    'file'              => 'openx_manager.settings.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_openx_manager_settings'),
    'title'             => 'OpenX manager',
  );
  return $items;
}

/**
 * Ask, if not already, a new session ID from OpenX
 *
 * @param $check_only
 *   Boolean. TRUE if its only to check if the session was already opened.
 * @return
 *   String. The full session ID, used on every further communication.
 */
function _openx_manager_session($check_only = FALSE) {
  static $session_id;
  if (!$check_only and !$session_id) {
    $session_id = xmlrpc(
      'http://'. variable_get('openx_manager_server', '') .'/www/api/v1/xmlrpc/LogonXmlRpcService.php',
      'logon',
      variable_get('openx_manager_username', ''),
      variable_get('openx_manager_password', '')
    );
  }
  return $session_id;
}
