<?
// $Id$
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file
 * Control a OpenX server from distance.
 */

/**
 * The main interface with the OpenX API
 *
 * @param $op
 *   String. The operation to be done
 * @param ...
 *   Any. Any needed data to execute the API operation.
 */
function _openx_manager_api($op) {
  module_load_include('api.inc', 'openx_manager');
  $args = func_get_args();
  return call_user_func_array('_openx_manager_call', $args);
}

/**
 * Implementation of hook_exit().
 */
function openx_manager_exit() {
  // Close the connextion with OpenX server, if opened.
  if (_openx_manager_session(TRUE)) {
    xmlrpc(
      'http://'. variable_get('openx_manager_server', '') .'/www/api/v1/xmlrpc/LogonXmlRpcService.php',
      'logoff',
      _openx_manager_session()
    );
  }
}

/**
 * Implementation of hook_form_alter().
 */
function openx_manager_form_openx_banner_node_form_alter(&$form, $form_state) {
  $form['buttons']['#weight'] = 99;
  $form['#theme']             = 'openx_banner_form';
}

/**
 * Implementation of hook_form_alter().
 */
function openx_manager_form_openx_zone_node_form_alter(&$form, $form_state) {
  drupal_add_js(drupal_get_path('module', 'openx_manager') .'/openx_manager.zone.js');
}

/**
 * Implementation of hook_link().
 */
function openx_manager_link($type, $object, $teaser = FALSE) {
  if ($type == 'node' and empty($teaser)) {
    if ($object->type == 'openx_advertiser' and user_access('create openx campaigns')) {
      $links['create_campaign'] = array(
        'title'       => t('Create a new Campaign'),
        'href'        => 'node/add/openx-campaign',
        'query'       => array('oaid' => $object->oaid, 'nid' => $object->nid),
      );
      return $links;
    }
    elseif ($object->type == 'openx_campaign' and user_access('create openx banners')) {
      $links['create_banner'] = array(
        'title'       => t('Create a new Banner'),
        'href'        => 'node/add/openx-banner',
        'query'       => array('ocid' => $object->ocid, 'nid' => $object->nid),
      );
      return $links;
    }
    elseif ($object->type == 'openx_publisher' and user_access('create openx zones')) {
      $links['create_zone'] = array(
        'title'       => t('Create a new Zone'),
        'href'        => 'node/add/openx-zone',
        'query'       => array('opid' => $object->opid, 'nid' => $object->nid),
      );
      return $links;
    }
  }
}

/**
 * Implementation of hook_menu().
 */
function openx_manager_menu() {
  $items['admin/settings/openx-manager'] = array(
    'access arguments'  => array('administer a OpenX server'),
    'description'       => 'Control a OpenX server from here',
    'file'              => 'openx_manager.settings.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_openx_manager_settings'),
    'title'             => 'OpenX manager',
  );
  $items['admin/settings/openx-manager/import'] = array(
    'access arguments'  => array('administer a OpenX server'),
    'description'       => 'Import data from OpenX server',
    'file'              => 'openx_manager.settings.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_openx_manager_import'),
    'title'             => 'OpenX data import',
  );
  return $items;
}

/**
 * Implementation of hook_node_info().
 */
function openx_manager_node_info() {
  return array(
    'openx_advertiser' => array(
      'description' => t('OpenX Advertisers'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_advertiser',
      'name'        => t('Advertiser'),
    ),
    'openx_banner' => array(
      'description' => t('OpenX Banners'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_banner',
      'name'        => t('Banner'),
    ),
    'openx_campaign' => array(
      'description' => t('OpenX Campaigns'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_campaign',
      'name'        => t('Campaign'),
    ),
    'openx_manager' => array(
      'description' => t('OpenX Managers'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_manager',
      'name'        => t('Manager'),
    ),
    'openx_publisher' => array(
      'description' => t('OpenX Publishers'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_publisher',
      'name'        => t('Publisher'),
    ),
    'openx_user' => array(
      'description' => t('OpenX Users'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_user',
      'name'        => t('User'),
    ),
    'openx_zone' => array(
      'description' => t('OpenX Zones'),
      'has_body'    => FALSE,
      'module'      => 'openx_node_zone',
      'name'        => t('Zone'),
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function openx_manager_perm() {
  return array(
    'create openx advertisers', 'edit own openx advertisers',
    'create openx banners',     'edit own openx banners',
    'create openx campaigns',   'edit own openx campaigns',
    'create openx managers',    'edit own openx managers',
    'create openx publishers',  'edit own openx publishers',
    'create openx users',       'edit own openx users',
    'create openx zones',       'edit own openx zones',
  );
}

/**
 * Ask, if not already, a new session ID from OpenX
 *
 * @param $check_only
 *   Boolean (optional). TRUE if its only to check if the session was already opened.
 * @param $server
 *   String (optional). The OpenX server URL.
 * @param $username
 *   String (optional). The OpenX server account username.
 * @param $password
 *   String (optional). The OpenX server account password.
 * @return
 *   String. The full session ID, used on every further communication.
 */
function _openx_manager_session($check_only = FALSE, $server = NULL, $username = NULL, $password = NULL) {
  static $session_id;
  if (!$check_only and !$session_id) {
    if (empty($server) and empty($username) and empty($password)) {
      $server   = variable_get('openx_manager_server', '');
      $username = variable_get('openx_manager_username', '');
      $password = variable_get('openx_manager_password', '');
    }

    $session_id = xmlrpc(
      $server .'/www/api/v1/xmlrpc/LogonXmlRpcService.php',
      'logon',
      $username,
      $password
    );
  }
  return $session_id;
}

/**
 * Implementation of hook_theme().
 */
function openx_manager_theme() {
  return array(
    'openx_advertiser' => array(
      'file'      => 'openx_manager.advertiser.inc',
      'arguments' => array('node'),
    ),
    'openx_banner' => array(
      'file'      => 'openx_manager.banner.inc',
      'arguments' => array('node'),
    ),
    'openx_banner_form' => array(
      'file'      => 'openx_manager.banner.inc',
      'arguments' => array('form'),
    ),
    'openx_campaign' => array(
      'file'      => 'openx_manager.campaign.inc',
      'arguments' => array('node'),
    ),
    'openx_manager' => array(
      'file'      => 'openx_manager.manager.inc',
      'arguments' => array('node'),
    ),
    'openx_publisher' => array(
      'file'      => 'openx_manager.publisher.inc',
      'arguments' => array('node'),
    ),
    'openx_user' => array(
      'file'      => 'openx_manager.user.inc',
      'arguments' => array('node'),
    ),
    'openx_zone' => array(
      'file'      => 'openx_manager.zone.inc',
      'arguments' => array('node'),
    ),
  );
}

/**
 * Implementation of hook_access().
 *
 * For Advertisers
 */
function openx_node_advertiser_access($op, $node, $account) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Advertisers
 */
function openx_node_advertiser_delete(&$node) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Advertisers
 */
function openx_node_advertiser_form(&$node, $form_state) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Advertisers
 */
function openx_node_advertiser_insert(&$node) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Advertisers
 */
function openx_node_advertiser_load(&$node) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Advertisers
 */
function openx_node_advertiser_update(&$node) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Advertisers
 */
function openx_node_advertiser_validate(&$node) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_advertiser_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('advertiser.inc', 'openx_manager');
  return _openx_node_advertiser_view($node, $teaser, $page);
}

/**
 * Implementation of hook_access().
 *
 * For Banners
 */
function openx_node_banner_access($op, $node, $account) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Banners
 */
function openx_node_banner_delete(&$node) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Banners
 */
function openx_node_banner_form(&$node, $form_state) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Banners
 */
function openx_node_banner_insert(&$node) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Banners
 */
function openx_node_banner_load(&$node) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Banners
 */
function openx_node_banner_update(&$node) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Banners
 */
function openx_node_banner_validate(&$node) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_banner_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('banner.inc', 'openx_manager');
  return _openx_node_banner_view($node, $teaser, $page);
}

/**
 * Implementation of hook_access().
 *
 * For Campaigns
 */
function openx_node_campaign_access($op, $node, $account) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Campaigns
 */
function openx_node_campaign_delete(&$node) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Campaigns
 */
function openx_node_campaign_form(&$node, $form_state) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Campaigns
 */
function openx_node_campaign_insert(&$node) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Campaigns
 */
function openx_node_campaign_load(&$node) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Campaigns
 */
function openx_node_campaign_update(&$node) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Campaigns
 */
function openx_node_campaign_validate(&$node) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_campaign_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('campaign.inc', 'openx_manager');
  return _openx_node_campaign_view($node, $teaser, $page);
}

/**
 * Implementation of hook_access().
 *
 * For Managers
 */
function openx_node_manager_access($op, $node, $account) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Managers
 */
function openx_node_manager_delete(&$node) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Managers
 */
function openx_node_manager_form(&$node, $form_state) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Managers
 */
function openx_node_manager_insert(&$node) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Managers
 */
function openx_node_manager_load(&$node) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Managers
 */
function openx_node_manager_update(&$node) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Managers
 */
function openx_node_manager_validate(&$node) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_manager_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('manager.inc', 'openx_manager');
  return _openx_node_manager_view($node, $teaser, $page);
}

/**
 * Implementation of hook_access().
 *
 * For Publishers
 */
function openx_node_publisher_access($op, $node, $account) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Publishers
 */
function openx_node_publisher_delete(&$node) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Publishers
 */
function openx_node_publisher_form(&$node, $form_state) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Publishers
 */
function openx_node_publisher_insert(&$node) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Publishers
 */
function openx_node_publisher_load(&$node) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Publishers
 */
function openx_node_publisher_update(&$node) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Publishers
 */
function openx_node_publisher_validate(&$node) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_publisher_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('publisher.inc', 'openx_manager');
  return _openx_node_publisher_view($node, $teaser, $page);
}

/**
 * Implementation of hook_access().
 *
 * For Users
 */
function openx_node_user_access($op, $node, $account) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Users
 */
function openx_node_user_delete(&$node) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Users
 */
function openx_node_user_form(&$node, $form_state) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Users
 */
function openx_node_user_insert(&$node) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Users
 */
function openx_node_user_load(&$node) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Users
 */
function openx_node_user_update(&$node) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Users
 */
function openx_node_user_validate(&$node) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_user_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('user.inc', 'openx_manager');
  return _openx_node_user_view($node, $teaser, $page);
}

/**
 * Implementation of hook_access().
 *
 * For Zones
 */
function openx_node_zone_access($op, $node, $account) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_access($op, $node, $account);
}

/**
 * Implementation of hook_delete().
 *
 * For Zones
 */
function openx_node_zone_delete(&$node) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_delete($node);
}

/**
 * Implementation of hook_form().
 *
 * For Zones
 */
function openx_node_zone_form(&$node, $form_state) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_form($node, $form_state);
}

/**
 * Implementation of hook_insert().
 *
 * For Zones
 */
function openx_node_zone_insert(&$node) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_insert($node);
}

/**
 * Implementation of hook_load().
 *
 * For Zones
 */
function openx_node_zone_load(&$node) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_load($node);
}

/**
 * Implementation of hook_update().
 *
 * For Zones
 */
function openx_node_zone_update(&$node) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_update($node);
}

/**
 * Implementation of hook_validate().
 *
 * For Zones
 */
function openx_node_zone_validate(&$node) {
  module_load_include('zone.inc', 'openx_manager');
  return _openx_node_zone_validate($node);
}

/**
 * Implementation of hook_view().
 *
 * For Advertisers
 */
function openx_node_zone_view(&$node, $teaser = FALSE, $page = FALSE) {
  module_load_include('zone.inc', 'openx_zone');
  return _openx_node_zone_view($node, $teaser, $page);
}
